### ISSUE TITLE
Moving a tab to the background inflates LCP

### ISSUE THREAD

**Issue by dbreeze-veeqo** [aws-observability/aws-rum-web#245] opened 2022-09-30 12:48 UTC
The LCP measure uses a PerformanceObserver. As PerformanceObservers don't run in the background, if a user visits a page and minimizes / changes browser tab before the LCP is measured then the LCP value will be the time the browser tab is brought back to the foreground

**Comment by dbreeze-veeqo** [comment] 2022-10-07 07:42
Any updates?

**Comment by qhanam** [comment] 2022-10-17 18:27
Hi @dbreeze-veeqo, we bumped the web vitals version (from v1 to v3) in release 1.9.x. Could you check to see if that resolved the issue?

**Comment by MyGuySi** [comment] 2022-11-08 15:21
Hey @qhanam, are you able to clarify whether RUM detects and filters out LCP events for pages that were opened in the background? It looks like the `web-vitals` library will record LCP for all pages regardless of whether they were opened in the background or not, so I don't think bumping the version will have any effect on this issue. We're still seeing very large spikes in LCP (as high as 2 hours).

https://web.dev/lcp/#when-is-largest-contentful-paint-reported

**Comment by qhanam** [comment] 2022-11-11 23:18
It looks like the standard approach to handle this case is to discard the LCP values. Specifically, when the page was loaded in the background, the CloudWatch RUM web client should not record the LCP.

**Comment by limhjgrace** [comment] 2022-11-15 21:18
Hello, I've verified that after bumping the `web-vitals` library for the web client, LCP for pages opened in the background is not recorded as I was unable to reproduce this issue using web client release 1.11.x. As Quinn mentioned, this update is available from release 1.9.x and higher. Could you verify if this issue still persists with the newer web client releases? If not, feel free to close this issue!

**Closed** 2022-11-22 23:50 UTC
